<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.152.0" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.200" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ImageForensics.Core/ImageForensics.Core.csproj" />
    <ProjectReference Include="../../src/ImageForensics.Forensics/ImageForensics.Forensics.csproj" />
    <ProjectReference Include="../../src/ImageForensics.Reporting/ImageForensics.Reporting.csproj" />
    <ProjectReference Include="../../src/ImageForensics.Imaging/ImageForensics.Imaging.csproj" />
    <ProjectReference Include="../../src/ImageForensics.Metadata/ImageForensics.Metadata.csproj" />
    <ProjectReference Include="../../src/ImageForensics.Storage/ImageForensics.Storage.csproj" />
  </ItemGroup>
</Project>
